# Generated by Django 3.1 on 2020-08-06 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200806_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comm',
            field=models.CharField(default=datetime.datetime(2020, 8, 6, 12, 31, 29, 135813, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 18, 1, 4, 131824)),
        ),
    ]
