# Generated by Django 3.1 on 2020-08-06 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200806_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 18, 5, 19, 788597)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='20:00'),
        ),
    ]
