# Generated by Django 3.1 on 2020-08-06 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200806_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comm',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 6, 18, 6, 24, 512283)),
        ),
    ]
