# Generated by Django 3.1 on 2020-08-07 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200806_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 7, 12, 21, 30, 200058)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 8, 7, 6, 51, 30, 200058, tzinfo=utc)),
        ),
    ]
