# Generated by Django 3.1 on 2020-08-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200807_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
